### ISSUE TITLE
Sly 3 21:9 Ultrawide Mod

### ISSUE THREAD

**Issue by John-Ivar** [zzamizz/weed-sheet#20]
I've been playing through the first and second Sly games with 21:9 patches, and it looks and feels absolutely awesome on my 21:9 screen. Problem is, I've never found or been able to create a patch for the third game, and going back to 16:9 just isn't as cool. Is this something you've managed to create or is it even possible/functional?

Many thanks in advance, and sorry if this is not the right place to request this.

**Comment by zzamizz** [comment]
[sly 3 ntsc ultrawide.zip](https://github.com/user-attachments/files/17345500/sly.3.ntsc.ultrawide.zip)
try that, should be good enough. a rough version still so im not uploading it yet

**Comment by damario123** [comment]
Also zami uh do u have the 4:3 sly 2 ultra wide mod

**Comment by John-Ivar** [comment]
Thank you so much for the quick reply, zami. I've tested it for about an hour now and it works brilliantly! All the work you're doing here is exceptional and makes it so much fun returning to the series!
